inherit_from: ./configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-3.0, 8.0], [-2.0, 5.0], [-8.0, 4.0]]

meshing:
  gt_mesh_path: '/home/yzhang/data/ScanNet/scans/scene0054_00/scene0054_00_vh_clean.ply'
  eval_rec: True

data:
  input_folder: /home/yzhang/data/ScanNet/scans/scene0054_00
  output: /home/yzhang/exps/goslam/scannet/0054/mono
